name: Tests

on: ['push', 'pull_request']

jobs:
  ci:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest]
        php: ['8.1']
        dependency-version: [prefer-stable]

    name: PHP ${{ matrix.php }} - ${{ matrix.os }} - ${{ matrix.dependency-version }}

    steps:

    - name: Checkout
      uses: actions/checkout@v3

    - name: Setup PHP
      uses: shivammathur/setup-php@v2
      with:
        php-version: ${{ matrix.php }}
        tools: composer
        coverage: none

    - name: Install PHP dependencies
      run: composer update --${{ matrix.dependency-version }} --no-interaction --no-progress --ansi

    - name: Run wkhtmltopdf
      run: vendor/h4cc/wkhtmltopdf-amd64/bin/wkhtmltopdf-amd64 -V

    - name: Run wkhtmltoimage
      run: vendor/h4cc/wkhtmltoimage-amd64/bin/wkhtmltoimage-amd64 -V
